version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      STORAGE_TYPE: redis
      REDIS_HOST: redis
  redis:
    image: "redis:alpine"
